export const DARK = {
  mode: 'DARK',
  BACKGROUND_COLOR: '#000000',
  STATUS_BAR_STYLE: 'light-content',
  PRIMARY_TEXT_COLOR: 'white',
  SECONDARY_TEXT_COLOR: '#DBFF00',
  PRIMARY_BUTTON: '#DBFF00',
  PRIMARY_BUTTON_TEXT: '#000000',
  SECONDARY_BUTTON: '#272727',
  SECONDARY_BUTTON_TEXT: '#DBFF00',
  PRIMARY_TEXT_INPUT: '#272727',
  PRIMARY_TEXT_INPUT_PLACEHOLDER: '#515151',
};
